version: '5'
services:


  app:
    container_name: app_test
    image: laravel:test
    restart: always

  web:
    container_name: nginx
    image: nginx:test
    ports:
      - "8080:80"
    depends_on:
      - app
    restart: always


volumes:
  pgdata:

  # cache:
  #   image: redis:alpine
  #   container_name: cache_test
  #   ports:
  #     - "6379:6379"
  #   restart: always

  # queue:
  #   image: com.selancar_app
  #   container_name: com.selancar_queue
  #   restart: always
  #   command: php artisan queue:work
  #   volumes:
  #     - ./:/var/www/

  # cron:
  #   image: com.selancar_app
  #   # build:
  #   #   context: ./
  #   #   dockerfile: docker/cron.dockerfile
  #   container_name: com.selancar_cron
  #   depends_on:
  #     - app
  #   volumes:
  #     - ./:/var/www 
  #     - ./docker/cron.sh:/var/www/docker/cron.sh
  #   command: ['chmod', '+x', '/var/www/docker/cron.sh']
  #   restart: always